### ISSUE TITLE
Unable to add word_count plugin

### ISSUE THREAD

**Issue by yoasty** [ONLYOFFICE/plugin-wordscounter#4] opened 2021-01-22 11:10 UTC
**Do you want to request a *feature* or report a *bug*?**
Probably a bug. But maybe I just do it wrong
**What is the current behavior?**
I downloaded the word count plugin files.
https://www.onlyoffice.com/blog/2021/01/meet-new-plugins-for-onlyoffice-docs-telegram-html-and-word-counter/
then followed the instructions 
For desktop editors
Archive the plugin files (it must contain config.json, index.html, and pluginCode.js).
Change the file extension to .plugin.
Go to the Plugins tab, click Manage Plugins >> Add plugin, browse for the .plugin file.
I tried with all three copied to *.plugin I tried all combinations, but I cannot add it. I can click on the file, but nothing happens.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
as described above
**What is the expected behavior?**
for the plugin to be added through the menu
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Most recent dektop-editor version for appimage (6.1.0.90) and as installed deb (6.1.0.90) file on debian 10.

**Comment by ShockwaveNN** [comment] 2021-01-22 11:35
Hi, could you attach `plugin` file you get `config.json` and other file should be on top level of this archive, not in some subfolder

**Comment by yoasty** [comment] 2021-01-22 13:01
Ok it is just the 3 files from the downloaded plugin files:

I can only attach zip files. I use the index.html and config.json and from the  scripts folder the code.js file. Attached here as zip.
I have tried all combinations of *.plugin all three named plugin, the zip file named *.plugin. Nothing works.
[oop.zip](https://github.com/ONLYOFFICE/plugin-wordscounter/files/5855956/oop.zip)

**Comment by ShockwaveNN** [comment] 2021-01-22 13:13
You should not zip only 3 files, but all subdirectories in this directory

Duplicate of this:
https://github.com/ONLYOFFICE/plugin-wordscounter/issues/3

**Closed by ShockwaveNN** 2021-01-22 13:13 UTC

**Comment by yoasty** [comment] 2021-01-22 15:55
The solution is that the zip-file that can be downloaded needs to be renamed to *.plugin.  Not any of the files in it. Only the zip-file.  
https://github.com/ONLYOFFICE/plugin-wordscounter   on the right top [code]  then click download zip file. rename the zip-file- to wordcounts.plugin
then add the plugin under plugin/settings/add plugin in onlyoffice.

**Comment by ShockwaveNN** [comment] 2021-01-25 07:08
> The solution is that the zip-file that can be downloaded needs to be renamed to .plugin

You better not to download zip files via github, but clone this repo via `git`, it will not contain any extra folders

**Comment by JoelForamitti** [comment] 2021-02-26 09:13
Hi @yoasty. This description is absolutely crucial to manage to install the plugin. The onlyoffice API is otherwise very misleading (it says that there should be a pluginCode.js file, for example, and does not say which archive format to use). I would suggest to add this description to the readme file

> The solution is that the zip-file that can be downloaded needs to be renamed to _.plugin. Not any of the files in it. Only the zip-file. https://github.com/ONLYOFFICE/plugin-wordscounter on the right top [code] then click download zip file. extract the zip-file to a file in plugin-wordscounter-master/_ go into the directory and zip all files and folders in it (buut without plugin-wordscounter-master)
> The zip-file should have the foollwing structur:
> resources
> scripts
> translations
> config.json
> README.md
> index.html
> 
> rename the zip-file- to wordcounts.plugin
> then add the plugin under plugin/settings/add plugin in onlyoffice.

**Comment by ShockwaveNN** [comment] 2021-02-26 10:15
@JoelForamitti Thanks for your concert, our documentation team told me that we are currently working on new version of https://api.onlyoffice.com/plugin/installation page with more details
